export const data = {
    "sleepDuration ": 30000,
    "cmdPath": '/src/cmd/',
    "heartbeat": true,
    "enabled": true,
    "sleepDuration": 2000,
    "heartbeatDuration": 1000 * 60 * 10, 
    "verbosity": 0,
    "steps": ['initConfig','incrBudget', 'divdBudget', 'scanBotnet', 'scanPublic', 'scanHacknet', 'runBotnet', 'runPublic', 'runHacknet', 'runHacker'],
    "steps.initConfig.file": 'init_config.js',
    "steps.initConfig.enabled": true,
    "steps.incrBudget.file": 'increase_budget.js',
    "steps.incrBudget.enabled": true,
    "steps.divdBudget.file": 'divide_budget.js',
    "steps.divdBudget.enabled": true,
    "steps.scanBotnet.file": 'scan_botnet.js',
    "steps.scanBotnet.enabled": true,
    "steps.scanPublic.file": 'scan_public.js',
    "steps.scanPublic.enabled": true,
    "steps.scanHacknet.file": 'scan_hcknet.js',
    "steps.scanHacknet.enabled": true,
    "steps.diagnoseBotnet.file": 'diag_botnet.js',
    "steps.diagnoseBotnet.enabled": true,
    "steps.diagnosePublic.file": 'diag_public.js',
    "steps.diagnosePublic.enabled": true,
    "steps.diagnoseHacknet.file": 'diag_hcknet.js',
    "steps.diagnoseHacknet.enabled": true,
    "steps.runBotnet.file": 'run_botnet.js',
    "steps.runBotnet.enabled": true,
    "steps.runPublic.file": 'run_public.js',
    "steps.runPublic.enabled": true,
    "steps.runHacknet.file": 'run_hcknet.js',
    "steps.runHacknet.enabled": true,
    "steps.runHacker.file": 'run_hacker.js',
    "steps.runHacker.enabled": true,
    "steps.runBatcher.file": 'run_batchr.js',
    "steps.runBatcher.enabled": false
}